[project]
name = "arbitrage-find"
authors = ["Your Name <your.email@example.com>"]
description = "Cross-DEX arbitrage trade discovery and execution platform"
telemetry = false
requirements = []
[contracts.arbitrage-router]
path = "contracts/arbitrage-router.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
